title: michaelgraemeshort.github.io
email: michaelgraemeshort@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Nothing to see here
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: nope
github_username:  michaelgraemeshort

# Build settings
# markdown: kramdown (commented this out just to see what happens - nothing, if I understand the docs correctly, as kramdown is default)
theme: minima

header_pages:
 - about.md
 - certs.md
 - cv.md
 - links.md